### ISSUE TITLE
UnpicklingError when running demo

### ISSUE THREAD

**Issue by nicklothian-redmarker** [gurvindersingh/mlapp#1]
Following the instructions on the github page on OSX with Python 3.6.5 gives the following error. I've never seen this before, but I did notice some people have similar issues with models saved with joblib (eg https://stackoverflow.com/a/44852728/280795)

```[2018-11-23 22:08:44,929] [PID 1604] [MainThread] [None] [root] [INFO] Loading model: v1, architecture: resnet34, file: models/v1.pth
[2018-11-23 22:08:45 +1030] [1604] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/Users/myname/dev/prg/mlapp_test/mlapp/venv/lib/python3.6/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/Users/myname/dev/prg/mlapp_test/mlapp/venv/lib/python3.6/site-packages/gunicorn/workers/base.py", line 129, in init_process
    self.load_wsgi()
  File "/Users/myname/dev/prg/mlapp_test/mlapp/venv/lib/python3.6/site-packages/gunicorn/workers/base.py", line 138, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/Users/myname/dev/prg/mlapp_test/mlapp/venv/lib/python3.6/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/Users/myname/dev/prg/mlapp_test/mlapp/venv/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 52, in load
    return self.load_wsgiapp()
  File "/Users/myname/dev/prg/mlapp_test/mlapp/venv/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 41, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/Users/myname/dev/prg/mlapp_test/mlapp/venv/lib/python3.6/site-packages/gunicorn/util.py", line 350, in import_app
    __import__(module)
  File "/Users/myname/dev/prg/mlapp_test/mlapp/app.py", line 92, in <module>
    model.load()
  File "/Users/myname/dev/prg/mlapp_test/mlapp/model.py", line 73, in load
    learn.load(model, device=CONFIG[model]['device'])
  File "/Users/myname/dev/prg/mlapp_test/mlapp/venv/lib/python3.6/site-packages/fastai/basic_train.py", line 204, in load
    self.model.load_state_dict(torch.load(self.path/self.model_dir/f'{name}.pth', map_location=device))
  File "/Users/myname/dev/prg/mlapp_test/mlapp/venv/lib/python3.6/site-packages/torch/serialization.py", line 358, in load
    return _load(f, map_location, pickle_module)
  File "/Users/myname/dev/prg/mlapp_test/mlapp/venv/lib/python3.6/site-packages/torch/serialization.py", line 519, in _load
    magic_number = pickle_module.load(f)
_pickle.UnpicklingError: invalid load key, 'v'```

**Comment by gurvindersingh** [comment]
@nicklothian-redmarker  thanks for testing out. Can you provide some information as:
 - Model Architecture (Check if they are same as training and inference)
 - Classes (Check if they are same as during training and inference)
 - Version of fastai and pytroch.

If possible can you provide a way for me to reproduce this error. As error seems to be coming from pytorch, not even mlapp or fastai.

**Comment by nicklothian-redmarker** [comment]
I followed the instructions on the Github README:

```
git clone --depth 1 https://github.com/gurvindersingh/mlapp.git
cd mlapp
virtualenv .ve
source .ve/bin/activate
pip install -r requirements.txt
pip install torch_nightly -f https://download.pytorch.org/whl/nightly/cpu/torch_nightly.html
gunicorn app:app
```

`pip freeze` gives me:

```
astroid==2.0.4
atomicwrites==1.2.1
attrs==18.2.0
Bottleneck==1.2.1
certifi==2018.10.15
chardet==3.0.4
Click==7.0
cycler==0.10.0
cymem==2.0.2
cytoolz==0.9.0.1
dataclasses==0.6
dill==0.2.8.2
fastai==1.0.27
fastprogress==0.1.15
Flask==1.0.2
gevent==1.3.7
greenlet==0.4.15
gunicorn==19.9.0
humanfriendly==4.17
idna==2.7
isort==4.3.4
itsdangerous==1.1.0
Jinja2==2.10
kiwisolver==1.0.1
lazy-object-proxy==1.3.1
locustio==0.9.0
MarkupSafe==1.1.0
matplotlib==3.0.1
mccabe==0.6.1
molten==0.7.2
more-itertools==4.3.0
msgpack==0.5.6
msgpack-numpy==0.4.3.2
murmurhash==1.0.1
mypy-extensions==0.4.1
numexpr==2.6.8
numpy==1.15.4
pandas==0.23.4
Pillow==5.3.0
plac==0.9.6
pluggy==0.8.0
preshed==2.0.1
prometheus-client==0.4.2
py==1.7.0
pylint==2.1.1
pyparsing==2.3.0
pytest==3.10.0
python-dateutil==2.7.5
pytz==2018.7
PyYAML==3.13
pyzmq==17.1.2
regex==2018.11.3
requests==2.20.0
scipy==1.1.0
six==1.11.0
spacy==2.0.16
thinc==6.12.0
toolz==0.9.0
torch-nightly==1.0.0.dev20181122
torchvision-nightly==0.2.1
tqdm==4.28.1
typed-ast==1.1.0
typing==3.6.6
typing-extensions==3.6.6
typing-inspect==0.3.1
ujson==1.35
urllib3==1.24.1
Werkzeug==0.14.1
wrapt==1.10.11
wsgicors==0.7.0
```

Are there any other details which are useful?

**Comment by gurvindersingh** [comment]
Ok it seems that you are missing git-lfs package which was needed to download the `v1.pth` file. It is around 87MB or so. Can you check the size of this file in your folder otherwise try to clone the repo again once you have the `git-lfs` installed.

**Comment by nicklothian-redmarker** [comment]
Thanks, that fixed it.

This is an unrelated issue, and sorry for not raising it separately. 

I've only does this kind of thing in Flask before. I like all the integration of Molten, but in Flask I can get the Swagger screen to show a file upload button. 

Is there a way to do the same in Molten? I saw https://www.reddit.com/r/moltenframework/comments/9u7bl9/access_to_uploaded_file_content_and_test_with/ which seems related, but it's unclear if it is fixed. 

![image](https://user-images.githubusercontent.com/43659293/48977862-a5d8c980-f0f2-11e8-8b50-b511856ecef7.png)

**Comment by gurvindersingh** [comment]
Good that the issue was fixed. Regarding file upload that issues was fixed and you should be able to test with the file upload test as mentioned in the docs under `Design` section. You need to choose `multipart/form-data` as content type and click `Try It Out` button to see upload option.

**Comment by nicklothian-redmarker** [comment]
Ok, that's strange. I raised this because this is what I see:

![image](https://user-images.githubusercontent.com/43659293/48992771-99ec1680-f189-11e8-8dcc-23d63b39c156.png)

**Comment by nicklothian-redmarker** [comment]
Oh I get it - I can choose the content type on the Swagger interface. Obvious now I see it.

Apologies for the stupid question.

**Comment by gurvindersingh** [comment]
No worries, glad that things worked out !!
